name: Update

on:
  workflow_dispatch:
  push:
#   schedule:
#     - cron:  '5 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      run: |
        python analysis.py
    - name: Commit and push changes
      if: github.ref == 'refs/heads/master'
      run: |
        git config user.name "Adam Jones"
        git config user.email "domdomegg+git@gmail.com"
        git add -A
        git diff-index --quiet HEAD || git commit -a -m "[bot] Update chart for $(date --iso-8601)"
        git push
